# docker-compose-monitoring.yml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: gusgus9836!
      MYSQL_DATABASE: cloud4
      MYSQL_USER: elice
      MYSQL_PASSWORD: gusgus9836!
    ports:
      - "3306:3306"

  application:
    container_name: board
    #    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloud4
      SPRING_DATASOURCE_USERNAME: elice
      SPRING_DATASOURCE_PASSWORD: gusgus9836!

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
