server:
  port: 5000

spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: html
#    cache: false
  jpa:
    defer-datasource-initialization: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/cloud4?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hyun
    password: gusgus9836!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB